int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int halp(int c, int i);
int is_prime_number(int n);
int hai(int n, int d);
int _sqrt(int x, int i);
int is_palindrome(char *s);
int get_length(char *s);
int my_pal(char *s, int l);
int wildcmp(char *s1, char *s2);
int findsrc(char *s, char c, int i, int p);
void _puts_recursion(char *s);
int wildcmp(char *s1, char *s2);
int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int square(int n, int val);
int _sqrt_recursion(int n);
int check_prime(int n, int resp);
int is_prime_number(int n);
int last_index(char *s);
int check(char *s, int start, int end, int pair);
int is_palindrome(char *s);
int checker(char *s1, char *s2, int a, int b, int wildUsed);
int wildcmp(char *s1, char *s2);
